name: Playwright Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  e2e_tests:
    name: 'E2E Tests (${{ matrix.runner }})'
    timeout-minutes: 60
    strategy:
      # Allow other matrix jobs to continue if one fails
      fail-fast: false
      matrix:
        runner:
          - blacksmith-2vcpu-ubuntu-2204
          - blacksmith-4vcpu-ubuntu-2204
          - blacksmith-8vcpu-ubuntu-2204
          - blacksmith-16vcpu-ubuntu-2204
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Copy env
        run: cp .env.example .env

      - uses: ./.github/actions/node-install

      - name: Start Services
        run: npm run dx:up

      - uses: ./.github/actions/playwright-install

      - name: Create the database
        run: npm run prisma:migrate-dev

      - name: Seed the database
        run: npm run prisma:seed

      - uses: ./.github/actions/cache-build

      - name: Run Playwright tests
        run: npm run ci
        env:
          # Needed since we use next start which will set the NODE_ENV to production
          NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH: './example/cert.p12'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
